name: 🕒 Daily Auto Commit

on:
  schedule:
    - cron: "15 8 * * *"  # 11:15 AM Kenya time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update log.txt with timestamp
        run: echo "Auto-commit: $(date)" >> log.txt

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🕒 Daily auto-commit: $(date)" || echo "Nothing to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
